/** Auto-generated by scripts/write-app-version.mjs — do not edit */
export const APP_VERSION = {
  "versionCode": 15,
  "versionName": "1.4.1",
  "apkUrl": "https://ballpwal.org/downloads/9mix-football-v15.apk",
  "apkUrlSite": "https://ballpwal.org/downloads/9mix-football-v15.apk",
  "apkUrlCdn": "https://ballpwal.org/downloads/9mix-football-v15.apk",
  "forceUpdate": true,
  "releaseNotes": "ပင်မ ပြင်ဆင်ချက် + Live Chat — v15",
  "releaseFeatures": [
    "ပင်မ — ပြီးသွားပွဲ မပြတော့၊ လာမည့်ပွဲ ဦးစား",
    "Premier League / Champions League / World Cup — လောင်းမည် ခလုတ်",
    "ပွဲရလဒ် — မြန်ဆန်စွာ ရလဒ်ကြည့်ရှု",
    "Web Hero — ဘောလုံးကန် Live Animation",
    "Live Chat ချက်ချင်း မြင်ရမည်"
  ]
};
