/** Auto-generated by scripts/write-app-version.mjs — do not edit */
export const APP_VERSION = {
  "versionCode": 12,
  "versionName": "1.3.8",
  "apkUrl": "https://ballpwal.org/downloads/9mix-football-v12.apk",
  "apkUrlSite": "https://ballpwal.org/downloads/9mix-football-v12.apk",
  "apkUrlCdn": "https://ballpwal.org/downloads/9mix-football-v12.apk",
  "releaseNotes": "Live Chat ချက်ချင်း မြင်ရမည်၊ Update v12"
};
